### ISSUE TITLE
插件使用报错

### ISSUE THREAD

**Issue by 1529960009** [X-Zero-L/BingAIChat#1]
![image](https://github.com/X-Zero-L/BingAIChat/assets/45947734/a50e1c7e-751f-44bb-be19-ae85ec9f6326)

**Comment by X-Zero-L** [comment]
1.如果你还没有使用bingchat进行过会话，自己进官网开启一次对话后再获取cookies
2.如果使用的是梯子，考虑更换节点/换一个ip干净的梯子
3.考虑更新cookies

**Comment by X-Zero-L** [comment]
也可以试试这里提出的方法：[If you face the CaptchaChallenge like:](https://github.com/tom-snow/PyroEdgeGPTBot/issues/20#issuecomment-1586542261)
