### ISSUE TITLE
关于插件使用报错

### ISSUE THREAD

**Issue by cidaodao** [X-Zero-L/BingAIChat#2]
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/5bdec78f-21a7-4383-9d64-486ae83b6734)
楼主你好，萌新一枚，遇到这种情况不知道怎么解决

**Comment by X-Zero-L** [comment]
检查一下你的cookies

**Comment by X-Zero-L** [comment]
如果是偶发的就不用管了（

**Comment by cidaodao** [comment]
我的cookies是这样的 我也不知道咋填，我在服务器端用的clash默认的 然后我newbing网页也是正常可以聊天的
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/7f8c20ea-fa7b-4095-88e8-64a985cf85a0)

**Comment by X-Zero-L** [comment]
代理不是在cookies里填的，并且你加入这个proxy也没遵守json的格式

**Comment by cidaodao** [comment]
那代理应该填在哪里呀 我看您说把代理填在config.json.example再改成config.json不就是填在config.json里么，我之前发的那个是少了逗号的 （我不小心发错了），格式正确了就是报Failed：'name',

**Comment by X-Zero-L** [comment]
config和cookies不是一个东西

**Comment by maxesisn** [comment]
纯路人，实在是看不下去了！人家@cidaodao 懂的少一点怎么了？这个仓库的owner就知道嘲讽人家，就不给具体操作流程！这样下去，我们🇨🇳开源界怎么能有好的发展？！

**Comment by X-Zero-L** [comment]
你说的对但是你说的不对
________________________________
发件人: Maximilian Wu ***@***.***>
发送时间: 2023年7月19日 11:23
收件人: X-Zero-L/BingAIChat ***@***.***>
抄送: X-Zero-L ***@***.***>; Comment ***@***.***>
主题: Re: [X-Zero-L/BingAIChat] 关于插件使用报错 (Issue #2)


***@***.***<https://github.com/cidaodao> 懂的少一点怎么了？这个仓库的owner就知道嘲讽人家，就不给具体操作流程！这样下去，我们🇨🇳开源界怎么能有好的发展？！

**Comment by cidaodao** [comment]
> config和cookies不是一个东西

你说的太对了 我看走眼了

**Comment by cidaodao** [comment]
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/9e2c2065-b412-4693-bb0d-e9390f69e9ce)
]

**Comment by cidaodao** [comment]
我是用的clash for windows然后主程序默认端口设置的7890
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/36576c0d-c907-4445-bb54-24f99be5851f)
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/9349a082-5520-4cd5-9ac9-53dcf0496d5e)
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/10ec9704-b27b-4c2d-b867-0e4307b9fe52)

**Comment by cidaodao** [comment]
我是用的clash for windows然后主程序默认端口设置的7890 开的全局代理
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/72e7f2c7-51e9-479a-8b27-da95bc716203)
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/8bb4a360-ed56-44be-936b-2726963b6c61)
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/330bc00d-673d-43d3-b259-5d59d1e51404)

**Comment by X-Zero-L** [comment]
> ![image](https://user-images.githubusercontent.com/65718636/254465305-9e2c2065-b412-4693-bb0d-e9390f69e9ce.png) ]

pip install urllib3==1.25.11

**Comment by cidaodao** [comment]
![image](https://github.com/X-Zero-L/BingAIChat/assets/65718636/1d99b3ba-b385-4fe5-9ac7-a0f06a0608e6)

**Comment by X-Zero-L** [comment]
换个网/换个cookies/换个梯子
或者先写一个简单的request，代理填一下，看一下能不能正常使用代理
