### ISSUE TITLE
[使用问题]带图片的聊天很多时候读不到图片

### ISSUE THREAD

**Issue by Rlezzo** [X-Zero-L/BingAIChat#5]
bing [文本内容] [图片]：bing聊天,内容为必填,图片为可选,如果带有图片,bing会进行识别

成功案例：
bing:
这张图片显示了三个穿着防护服的人在路上跑。他们可能穿着危险物质处理的防护服，头戴头盔。路上除了这些人之外似乎空无一人。图片底部有中文文字：“女兵战备的瞬时切换”。

如果您需要更多信息或有其他问题，请告诉我！

多数失败案例：
bing: 请上传图片，我将为您提供内容描述。🖼️

suggestions:
我无法上传图片。
好的，谢谢你！
有其他问题吗？
————————————————————————
请问这个有解决办法吗？没有任何报错

**Comment by X-Zero-L** [comment]
这个我也救不了，理论上没报错的话图片都是上传成功的

**Comment by X-Zero-L** [comment]
你可以看一下图片是不是都有被识别到，目前是获取图片的url字段

**Comment by Rlezzo** [comment]
能成功的图可以多次成功，失败的图一直失败，可能和图片有什么关系吧，太玄学了

**Comment by X-Zero-L** [comment]
拉取最新代码再试试

**Comment by Rlezzo** [comment]
OK了，基本是挺稳了

**Comment by Rlezzo** [comment]
手机发bing + 图片的信息，bing看不到图片，pc端发的带图消息可以。
我觉得是图床的问题，我打印了url，都是可以访问的，但是pc端发送的图床链接是gchat.qpic.cn域名，而手机的是multimedia.nt.qq.com.cn的域名，可能后者bing访问不了？
